smallbets/userbase

README.md
Fixes:
* Npm install option for Windows WSL.
* Infrastructure failing if env var is not set.
=> Add documentation about WSL and Env vars

src/userbase-server/setup.js
The main reason for this namespacing change is to allow two stacks to run in the same AWS account.
- Better namespacing for DynamoDB tables
- Enabled continuous backups for DynamoDB
- Turned on server-side encryption on S3 (even though what we store is almost all already encrypted)
- Disabled public objects on S3
- Made all the DynamoDB table names plural
=> Clean up and harden AWS resources

src/proof-of-concept/client/components/User/UserForm.jsx, src/proof-of-concept/client/components/User/logic.js, src/userbase-js/api/auth.js, src/userbase-js/auth.js, src/userbase-js/config.js, src/userbase-js/errors/auth.js, src/userbase-js/index.js, src/userbase-js/utils.js, src/userbase-server/server.js, src/userbase-server/setup.js, src/userbase-server/user.js
Note that in the proof of concept, a user can now provide an email on sign up.
Here is what the forgot password mechanism looks like starting from the log in form:
- User fills out username input
- User clicks "forgot password"
- Client passes the server the username + app id
- Server sends the user's email an email containing a message with a temporary password string
- The user copy pastes that temporary password and can then use it to sign in
=> Forgot password

src/userbase-js/auth.js, src/userbase-js/errors/auth.js, src/userbase-js/index.js, src/userbase-js/utils.js, src/userbase-js/ws.js, src/userbase-server/server.js, src/userbase-server/user.js
- updateUser() takes in an object with possible properties of: username, password, email, profile
- if the developer provides an object with email or profile properties set but set with falsey values, this implementation assumes the developer is requesting to delete that property from the database
=> Implemented updateUser

src/proof-of-concept/client/components/User/UserForm.jsx, src/proof-of-concept/client/components/User/logic.js, src/userbase-js/auth.js, src/userbase-js/localData.js, src/userbase-js/ws.js
- rememberMe defaults to false 
- if rememberMe is false, userbase-js will not save a user's session, key, or key request to local storage
=> Implemented rememberMe option for signUp & signIn

package-lock.json, src/userbase-js/auth.js, src/userbase-js/style.css, src/userbase-server/admin-panel/package-lock.json
Based on [this comment](https://github.com/encrypted-dev/userbase/pull/12#discussion_r346573406)
Here's what the warning looks like when the user does not have rememberMe set to true:
(also added username input validation to forgotPassword in SDK)
=> When rememberMe false, ShowKey warns user won't be able to login w/o key

src/userbase-js/Crypto/sha-256.js, src/userbase-js/Crypto/utils.js, src/userbase-js/api/auth.js, src/userbase-js/auth.js, src/userbase-js/ws.js, src/userbase-server/server.js, src/userbase-server/user.js, src/userbase-server/utils.js
- Prevents server from ever seeing plaintext passwords
- Validate password length client-side now
- Note this will cause a breaking change on merge: current passwords won't work anymore
=> Hash passwords client-side (SHA-256) before sending to server

src/userbase-js/auth.js, src/userbase-js/config.js, src/userbase-js/db.js, src/userbase-js/errors/auth.js, src/userbase-js/errors/config.js, src/userbase-js/errors/db.js
Validate "is blank" exception condition against zero length string as opposed to !value. I'm guessing the existing implementation would return the wrong exception in the case the username or password input was string "false", boolean false, number zero or Null?
(Apologies if I've missed anything obvious, editing on mobile!)
=> Fix username and password "is blank" condition

src/userbase-js/auth.js, src/userbase-js/db.js, src/userbase-js/index.js, src/userbase-js/localData.js, src/userbase-js/ws.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/user.js
- After delete is called, the user is marked for deletion in DynamoDB
- User can't insert/update/delete, create a database, trigger the forgot password, authenticate a session, or sign in after deleting
- No other user can be created with same username even after the user is marked for deletion (until the future CRON job that removes user data from the server is implemented)
=> Implemented deleteUser

src/userbase-js/db.js, src/userbase-server/db.js, src/userbase-server/server.js
- Only 1 trip to server needed to create & open database
=> Rolled createDatabase up into openDatabase server-side

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx, src/userbase-server/admin-panel/components/Dashboard/logic.js, src/userbase-server/admin-panel/style.css, src/userbase-server/admin.js
=> Allow admins to create multiple apps

src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/user.js
=> Enable admin to delete user

src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js
=> Implemented admin forgot password

.eslintignore, .eslintrc.js, package.json
Made a few changes so we can run a lint script from the project root. Notes in commit messages.
=> Setup linting to run from root

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/config.js, src/userbase-server/admin-panel/index.html, src/userbase-server/admin.js, src/userbase-server/package-lock.json, src/userbase-server/package.json, src/userbase-server/server.js, src/userbase-server/stripe.js
1. I saw that redirecting users to [Stripe’s Checkout form](https://stripe.com/docs/payments/checkout) is the simplest approach to get working. The user hits the "Purchase Subscription" button on our site and is redirected to a Stripe-hosted website that has a pre-designed checkout form.
2. There is a [Client-side only integration](https://stripe.com/docs/payments/checkout/client-only) which at first seemed like the simplest way to collect payments, however, it’s a bit more complex to guarantee that our backend knows when a customer pays (among other more minor drawbacks).
3. Thus, I went with the [Stripe Checkout client & sever integration](https://stripe.com/docs/payments/checkout/subscriptions/starting). I still use Stripe’s checkout form hosted on their site as you can see in the gif. …
=> Stripe integration

src/userbase-server/admin.js
Prior to this PR, I was creating an admin's associated Stripe "customer" on sign up. This meant someone running userbase-server would need a Stripe account to create an admin.
This PR ensures a developer running userbase-server won't need a Stripe account to create an admin.
It ensures that only 1 Stripe customer ID will ever be saved on an admin in DDB and therefore, only 1 Stripe customer ID will ever be used to create a payment session server-side for a single admin.
=> Create associated Stripe "customer" when an admin attempts to pay for a subscription the first time

src/userbase-js/src/auth.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/index.js, src/userbase-js/src/index.js, src/userbase-js/types/index.d.ts, src/userbase-server/user.js
- Rename object passed to userbase-js functions from "input" to "params"
- Ensure userbase-js exports correct "buildTransaction", not "transaction"
- Hashing server-side isn't async, remove await
- Don't allow access to sign in endpoints if user is deleted
=> Minor sdk v1 changes

src/proof-of-concept/server/app.js, src/userbase-server/server.js
Reminder disclaimer: will need to fix our poc deployment
=> Serve admin panel from root

src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin.js, src/userbase-server/server.js
=> Temporarily do not require payment for hackathon

cypress/config/ci.json, cypress/config/development.json, cypress/integration/login.spec.js, cypress/support/commands.js, src/userbase-server/setup.js
Fixed all the signin/signup tests to comply with v1 of our backend.
=> Signin test

src/userbase-server/setup.js
Ensures AWS region will always stick to `us-east-1` in prod and `us-west-2` in dev. Avoids restarting services in a new region in the event `getEC2Region()` times out
=> Default AWS region to us-east-1 if not in dev mode

src/userbase-js/src/api/auth.js, src/userbase-js/src/auth.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/ws.js, src/userbase-server/server.js, src/userbase-server/user.js
Also tried to make the code a bit cleaner by grouping password salts & key salts separately
=> Require userbase-js user to provide current password to update their password

src/userbase-server/server.js, src/userbase-server/ws.js
Some are pretty detailed, might get expensive. Specifically [this one](https://github.com/encrypted-dev/userbase/compare/ws-logging?expand=1#diff-c6842224b01f98a47fa1890c0e3842d3R257-R272)
Also all pongs are logged (but pings are not). Do we definitely want to log pongs? And should I look deeper into logging pings?
=> Added server-side logs for every WS request/response

src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin.js, src/userbase-server/server.js
Re-implemented payment & allowed override of Stripe redirect URL, since we can't trust browsers will provide the correct referer header in all circumstances
=> Stripe redirect v2

src/proof-of-concept/server/app.js, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js
=> Receive email updates checkbox on admin sign up

src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx
- Users sorted by creation date in descending order
- Dates formatted
- Apps sorted by name in ascending order (after lower cased)
=> Sort apps & users in admin panel + format date

cypress/integration/login.spec.js, src/proof-of-concept/client/components/User/logic.js, src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/localData.js, src/userbase-js/src/ws.js
- Session storage still takes precedence on init()
- If a user signs out from their sessionStorage session, then signs in with a localStorage session, init() will then sign the user back in with their localStorage session :)
=> Allow 3 options to rememberMe ['local','session','none'] default session

src/proof-of-concept/server/app.js, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/setup.js
- brought back forgotPassword/SES/email code that was mistakenly deleted. Admin's forgotPassword() working again
- Require the admin's old password (or temp password) to change their password in the admin-panel
- separate the form to change password. The CSS isn't super pretty, especially when the screen is shrunk. But I'm going to move on for now
=> Admin change pw

src/userbase-server/app.js
Just doing it server-side for now for easy error handling
=> Trim app names

.github/workflows/e2e-tests.yml, package-lock.json, package.json, src/userbase-js/package-lock.json
Update to cypress 3.8.3 to avoid Ubuntu 18.04 error.
=> Actions v2

cypress/integration/db-correctness.spec.js, src/userbase-js/src/auth.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/index.js, src/userbase-js/src/statusCodes.js, src/userbase-js/src/ws.js, src/userbase-server/server.js, src/userbase-server/statusCodes.js, src/userbase-server/ws.js, test/browser2/index.html
- Enforces a maximum of 25 requests per second over the WebSocket
- Once the limit of 25 is reached, an additional request is allowed every second
=> Rate limit requests over the WebSocket

.gitignore, cypress.json, cypress/integration/login.spec.js, cypress/integration/signup.spec.js, cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json, src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/logger.js, src/userbase-server/package-lock.json, src/userbase-server/package.json
Testing signup,
Failing tests (due to server errors) are:
1. Signup a new user, username too long
2. Signup with a null profile
3. Signup with a profile with a value with 0 length
=> Signup testing

src/userbase-server/db.js, src/userbase-server/package-lock.json, src/userbase-server/package.json, src/userbase-server/peers.js, src/userbase-server/server.js, src/userbase-server/setup.js
- Step 1: server listens on port 9000 exposing a route to notify it of any new transactions
- Step 2: on setup, server starts a 30 second interval to discover EC2 peers
- Step 3: when receiving a transaction, server broadcasts the transaction to all EC2 peers so that they push the transaction to all connected clients
=> First pass broadcast transactions to all EC2 hosts (enables horizontal scaling)

.github/workflows/e2e-tests.yml
Enable NPM cache in Github Action to speedup the CI process.
=> Enable NPM Cache - and performance optimizations

src/userbase-server/app.js, src/userbase-server/user.js
- also fixes bug where counter was incrementing before user finished creating account
=> Query for num app users rather than store stateful counter

src/userbase-js/CHANGELOG.md
- followed pattern from [keep a changelog](https://keepachangelog.com/en/1.0.0/)
- kept it to userbase-js
=> Started changelog for userbase-js

src/userbase-server/server.js, src/userbase-server/user.js, src/userbase-server/utils.js, src/userbase-server/ws.js
- Add logging for REST calls
- Add statusCode field
- Add response time to ws routes
- remove wsRes/wsReq prefixes (make them a flat object)
- add clientId
=> Improved logging

cypress/integration/login.spec.js
=> Remove unnecessary test checking userbase endpoint on window object

src/userbase-js/src/auth.js, src/userbase-js/types/index.d.ts, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/statusCodes.js, src/userbase-server/user.js
- updated Access Token REST endpoints to fit a more practical pattern
- access token now expected as Authorization header of type Bearer
- renamed "internal profile" to "protected profile"
```
POST https://v1.userbase.com/v1/api/admin/users/:userId
Authorization: Bearer <token>
Content-Type: application/json
{ "protectedProfile": { "hello, ": "world!" } }
```
```
GET https://v1.userbase.com/v1/api/admin/users/:userId
Authorization: Bearer <token>
```
=> Hardened Admin API & Access Token implementation

cypress/integration/Admin API/user.spec.js, src/userbase-server/admin.js, src/userbase-server/user.js
- Consistent error message structure across Admin API
- Added tests for GetUser and UpdateUser
=> Admin API final touch-ups before V1 release

src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/ProfileTable.jsx
Thank you @raae for the suggestion!
=> Display user metadata in admin panel

src/userbase-server/admin.js, src/userbase-server/app.js
Realized I needed to spread the result to get the next page for these queries (access tokens, list apps, list app users).
=> Fix pagination for some admin panel queries

src/userbase-js/src/api/auth.js
- catches network error as pointed out in issue #145
=> Handle xhr's onerror by throwing ServiceUnavailable

cypress/integration/db.spec.js, src/userbase-js/src/db.js, src/userbase-js/src/index.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-server/app.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/utils.js
Query for all of a user's databases with a new SDK function `getDatabases()`.
The userbase-js client handles pagination behind the scenes.
The function signature looks like this:
```
getDatabases(): Promise<DatabasesResult>
export interface DatabasesResult {
databases: Database[]
}
export interface Database {
databaseName: string
}
```
This function will be critical for data sharing. Once we get to sharing, each database will also have metadata, such as who the owner of the database is, access permissions to the database, and all other users who have access to the database.
The final function signature will look like this:
```
getDatabases(): Promise<DatabasesResult>
export interface DatabasesResult {
databases: Database[]
}
export interface Database {
databaseName: string
owner: boolean …
```
=> GetDatabases added to userbase-js

cypress/integration/Admin API/auth-token.spec.js, src/userbase-server/user.js
- enables a server to associate user with auth token
=> Admin API VerifyAuthToken returns userId

src/userbase-server/purge.js
When a user is permanently deleted, the Userbase server purges all of the user's data in a nightly purge process.
This PR patches a bug in the purge process where if a new user is created with the same username as the old user to be purged BEFORE the purge process had finished purging the old user's data, the purge process would delete the new user as well.
The bug is present with apps as well.
When deleting the user or app, make reference to the `user-id` or `app-id` in a DDB condition expression respectively. This makes sure the purge process only deletes the expected user or app.
=> Fix: purge deleted usernames & apps w same name as one being purged

src/userbase-js/src/db.js, src/userbase-server/app.js, src/userbase-server/db.js, src/userbase-server/stripe.js, src/userbase-server/user.js
Thanks to @agigleux for reporting in #174
=> Fix some mismatch # of params + impossible reference

cypress/integration/forgotPassword.spec.js, cypress/integration/updateUser.spec.js
Added Update user info testing.
The forgotPassword file was only renamed due to the a typo.
Only one test is failing, it will appear in the CI system, I believe is a real (small) bug.
=> Added user update tests, renamed file with typo

src/userbase-server/server.js
Fixes #196 
The rate limiter is particularly useful for the openDatabase, insertItem, updateItem, deleteItem, putTransaction functions. No need for it to be so draconian for the others.
=> Isolate 25 requests/s rate limiter to core data CRUD endpoints over WS

src/userbase-server/db.js, src/userbase-server/package-lock.json, src/userbase-server/package.json
Don't return databases with owners that have been permanently deleted
Fixes #198
=> Get databases permanent delete user behavior fix

cypress/integration/Database Correctness/attribution.spec.js, cypress/integration/Database Correctness/bundling.spec.js, cypress/integration/Database Correctness/transaction.spec.js, cypress/integration/Database Sharing/modify-permissions.spec.js, cypress/integration/Database Sharing/share-database.spec.js, cypress/integration/db.spec.js, cypress/integration/file-storage.spec.js, src/userbase-js/CHANGELOG.md, src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-server/db.js, src/userbase-server/package-lock.json, src/userbase-server/package.json, src/userbase-server/server.js, src/userbase-server/ws.js
This will only impact newly created databases.
items returned via the changeHandler in `openDatabase()` in newly created databases will look like this (new fields in **bold**):
- itemId
- item
- fileId
- fileName
- fileSize
- **createdBy**
- **updatedBy** [not present if not needed]
- **fileUploadedBy** [not present if not needed]
- **timestamp**
- **username** [not present if user deleted]
- **userDeleted** [boolean, only present if true]
=> Tx attribution

cypress/integration/Database Sharing/share-database.spec.js, src/userbase-js/CHANGELOG.md, src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/config.js, src/userbase-js/src/errors/db.js
=> Fix UserNotVerified error message

src/userbase-server/app.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/user.js
=> list database users endpoint

cypress/integration/Admin API/app.spec.js, cypress/integration/Admin API/database.spec.js, cypress/integration/Database Sharing/modify-permissions.spec.js, cypress/integration/Database Sharing/share-database.spec.js, cypress/integration/db.spec.js, cypress/support/utils.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/db.js, src/userbase-js/types/index.d.ts, src/userbase-server/app.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/user.js
Merges #214 and #215 + adds tests for ListDatabaseUsers
=> List database users

README.md, cypress/integration/Database Sharing/modify-permissions.spec.js, src/userbase-js/README.md, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/setup.js, src/userbase-server/utils.js
Credit to @Fubinator for the request
=> Allow users to revoke own access to database (#222)

cypress/integration/Database Correctness/bundling.spec.js, cypress/integration/Database Correctness/file-storage.spec.js, cypress/support/utils.js, src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/Crypto/aes-gcm.js, src/userbase-js/src/Crypto/diffie-hellman.js, src/userbase-js/src/api/auth.js, src/userbase-js/src/api/db.js, src/userbase-js/src/api/index.js, src/userbase-js/src/api/utils.js, src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/worker.js, src/userbase-js/src/ws.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/utils.js, src/userbase-server/ws.js
When a database grows 50kb, the Userbase client will bundle the database up, compress it, encrypt it, then store it on the server. Next time the user signs in and loads their data, they load the database from the bundle for speedy loading. This process is described further [here](https://github.com/smallbets/userbase/blob/e73a90e677f4ddb8e597eef3050778a4c35627c8/docs/userbase_architecture.md#bundling).
This PR brings a number of optimizations and safety improvements to the bundle process:
- The bundle is encrypted with a newly generated encryption key, which is then wrapped with a database's encryption key.
- The bundle is uploaded and downloaded in chunks to prevent overloading the server with large bundles.
- The client now uses a much faster encoding algorithm that maintains the size …
=> Optimize bundling

cypress/integration/Database Sharing/access-control.spec.js, cypress/integration/signIn.spec.js, package.json, src/userbase-js/CHANGELOG.md, src/userbase-js/package.json, src/userbase-js/src/Crypto/scrypt.js, src/userbase-js/src/auth.js, src/userbase-js/src/db.js, src/userbase-js/webpack.window.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/ws.js
- Setting write access control with users via transaction working + cleaned up access control code bloat
- enable compatibility with Cordova plugin
=> userbase-js v2.7.0

cypress/integration/Database Sharing/access-control.spec.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/statusCodes.js, src/userbase-server/ws.js
- server won't allow userbase-js clients <v2.7.0 to bundle transactions anymore, but they can read and interact with bundled databases just fine. [note: bundling happens in the background, this has no impact on devs or the Userbase SDK's API. purely a server-side change]
- if a user changes their username after receiving write access on an item, the database item will load with their current username set on the write access object, rather than the username set when they received write access.
- improved logging on web socket connection + database opening.
=> Bundling optimization + access control fixes

src/userbase-js/src/config.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-server/user.js
Return subscriptionPlanId on user (#266)
Push updated user to userbase-js `updateUserhandler` after a Stripe change (#267)
=> Stripe adds
