src/proof-of-concept/server/app.js, src/userbase-server/server.js, src/userbase-server/setup.js
Lets us send emails using Amazon SES.
Since emails can only be sent from a verified domain, I've added the domain in the config settings of userbase-server. The POC is using 'encrypted.dev', but the service will use 'userbase.dev'.
To use it, import 'setup' and use the sendEmail exported function. This is probably not the best place for it, but seemed good enough for now.
Also note that right now, our SES account can only send emails to verified recipients. So, make sure you verify your email address when testing: https://us-west-2.console.aws.amazon.com/ses/home?region=us-west-2#verified-senders-email: — We need to wait for Amazon to remove this limit.
=> Add SES integration

src/userbase-js/Crypto/index.js, src/userbase-js/Crypto/pbkdf.js, src/userbase-js/api/auth.js, src/userbase-js/auth.js, src/userbase-js/ws.js, src/userbase-server/server.js, src/userbase-server/user.js
- unless `passwordBasedKeyRecoveryEnabled` is set to false via the param to `signUp()`, an encryption key will be derived from the user's password via PBKDF2, this key will be used to encrypt the user's seed, and the encrypted seed will be stored on the server
- on signIn(), the encrypted seed will be returned to the client, then decrypted with the password. This way a user only needs their password to sign in by default
- updateUser() re-encrypts the seed using the new password if the user has password-based recovery enabled
=> Password-based key recovery enabled by default

src/userbase-js/auth.js, src/userbase-js/db.js, src/userbase-js/errors/index.js, src/userbase-js/ws.js, src/userbase-server/server.js
When the WebSocket connection drops, this PR ensures the client attempts to re-open the connection and then re-open already opened databases. As discussed, it uses a linear backoff of 1 second (i.e. attempt to reconnect in 1s, re-attempt in 2s on failure, re-attempt in 3s on failure) to a max of 30 seconds.
The server now explicitly sends a 'Ping' message to the client over the WebSocket every 30 seconds. If the client does not receive a 'Ping' message from the server every 30 seconds (+ latency), the SDK can assume the client's internet connection was dropped and triggers the reconnect. If the server does not receive a 'Pong' message from the client every 30 seconds, the server terminates the connection same as before.
When the WebSocket is in the process of reconnecting, all functions …
=> WebSocket auto reconnect

src/proof-of-concept/client/components/Dashboard/logic.js, src/userbase-js/db.js, src/userbase-js/errors/db.js, src/userbase-js/index.js, src/userbase-js/ws.js, src/userbase-server/db.js
- Renamed insert/update/delete to insertItem/updateItem/deleteItem in SDK
- limited the # of operations in a transaction to 10 server-side
- made WebSocket's Request error handling slightly cleaner
=> Small sdk updates

src/userbase-server/db.js, src/userbase-server/user.js
This PR fixes issues arising from concurrent DDB TransactionWrites. Note that it still seemed necessary to use DDB's TransactWrite for 2 things:
1. Creating a database is a DDB transaction that inserts both the `database` AND `userDatabase`. Complex nuance: a transaction conflict may arise if a user concurrently calls  `openDatabase` with the same name _before_ having successfully called it once, however this DDB transaction guarantees both `database` and `userDatabase` are created together (i.e. one can never exist without the other which would cause other potential safety issues). Even if this transaction conflict does arise though, [this query in the catch block](https://github.com/encrypted-dev/userbase/compare/tx-conflict?expand=1#diff-62050e09b89b49d8d0911769ef6bd8c7R129-R133) helps …
=> Fixed DDB transaction conflict on concurrent Userbase transactions, openDatabase, and signUp

src/proof-of-concept/webpack.config.js, src/userbase-js/config.js, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/logic.js, src/userbase-server/admin-panel/config.js, src/userbase-server/admin-panel/webpack.config.js, src/userbase-server/server.js
All server-side endpoints now have a `/v1` prefix with exception to the endpoint serving the admin panel. This way the admin panel is still reachable at `/admin` rather than `/v1/admin`.
=> Api versioning

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/user.js
As discussed, in addition to making admin accounts inaccessible after delete is called, all admin's apps become inaccessible to users on their next sign in.
Couple notes on this PR:
- In the gif, you'll see the admin can click their account in the top right which brings up a new page where the "Delete Account" button is. Planning to allow the admin to edit their account on that page as well (to change their name, email, password).
- I introduced a circular dependency in userbase-server. `admin.js` now imports `user.js`. `user.js` imports `admin.js`. The code compiles and runs fine, but it's a code smell I wanted to highlight. I would personally solve this with a general restructuring of the server into a pattern of controllers -> services -> db operations where each level has clear roles. …
=> Implemented delete admin

src/proof-of-concept/server/app.js, src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/setup.js
- Refactored "adminName" to "email" & validate emails on admin account creation and update server-side
- if admin updates email, server creates new DDB item and deletes old one inside a DDB tx
- client keeps admin's full name in local storage
- full name now must be provided to createAdmin endpoint
=> Admin update account

src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/types/index.d.ts, src/userbase-js/types/test.ts, src/userbase-js/types/tsconfig.json, src/userbase-js/types/tslint.json
This is still a WIP and it may make sense to wait until the API stabilizes a bit more before merging. It turns out the TS definitions for the API are quite simple (no generics required) so maintaining wont be a problem.
=> Introduce TypeScript declarations

src/userbase-js/db.js, src/userbase-server/db.js, src/userbase-server/ws.js
As discussed:
Allow a 10s buffer before triggering rollbacks upon finding a gap in DDB tx sequence numbers. Tested 1000 concurrent insertions (needed to raise [this timeout](https://github.com/encrypted-dev/userbase/compare/db-optimizations?expand=1#diff-94758e067438af2615c1d97a0f1c3d0fR61) for 1000 concurrent txs to finish on my machine)
"Currently we're writing a tx to DDB, and then we read the tx back from DDB to push it to the client over the WS. In theory, if the new tx's seq # is adjacent to the last seq # stored in the WS's state, we could just push the tx we've just written to the WS. No need to read it from DDB (since it's immutable, and nobody could have added a tx with that seq #)."
- @dvassallo
=> Db optimizations

src/userbase-server/db.js
- Accidentally broke this when rolling createDatabase up into openDatabase server-side
- When rolling createDatabase up into openDatabase server-side, I made the server enforce that the client pass the parameter `newDatabaseParams` to openDatabase. However, when re-opening the database, this param isn't necessary because we know the server shouldn't need to create a new database if one isn't found
- This fix removes the requirement to pass `newDatabaseParams` to the server when calling openDatabase so that when the client attempts to reopen a database after reconnecting the websocket, the client can do so without providing anything to `newDatabaseParams`
=> Fix: database reopens on websocket reconnect

src/userbase-server/utils.js, src/userbase-server/ws.js
- When calculating the size of a Userbase transaction's DDB item, the operations array was ignored and thus not triggering the bundling process
- Also made it clearer the function to get the size of a DDB item is an estimate
=> Fix: Ensure we correctly estimate the size of DDB items for Userbase transactions

src/userbase-js/src/ws.js, src/userbase-server/db.js, src/userbase-server/ws.js
When a bundle was stored for a user, the backend wasn't reading the bundle as expected (was getting transactions from DDB)
Fixed by getting bundle when [database.lastSeqNo === 0](https://github.com/encrypted-dev/userbase/pull/45/files#diff-c6842224b01f98a47fa1890c0e3842d3R50)
Race condition in the client between ApplyTransactions and BuildBundle. BuildBundle would sometimes run before ApplyTransactions finishes and the bundle sent to the server would be empty
Fixed by removing the 'BuildBundle' route and adding a [buildBundle boolean](https://github.com/encrypted-dev/userbase/pull/45/files#diff-c6842224b01f98a47fa1890c0e3842d3R157) to 'ApplyTransactions' payload so the client will always build the bundle after transactions are applied
=> Fix: bundling process working consistently

src/userbase-js/src/db.js, src/userbase-js/src/ws.js
The `changeHandler` was getting called [AFTER all transactions were applied](https://github.com/encrypted-dev/userbase/blob/4162cf97cca0f7a95553e62a1c0d8b01fdd89438/src/userbase-js/src/ws.js#L306-L307). This meant in a situation where a user attempts concurrent inserts, an insert could _sometimes_ resolve and return to the user BEFORE the `changeHandler` gets called.
This caused the test4 failure highlighted in PR #48
Here's the circumstance described:
1. Browser 1 inserts item foo [placing it in the array of unverified tx’s, then queues request()](https://github.com/encrypted-dev/userbase/blob/4162cf97cca0f7a95553e62a1c0d8b01fdd89438/src/userbase-js/src/db.js#L689-L699)
2. Browser 2 inserts item bar
3. Browser 1 receives transaction log with foo and bar and [applies this …
=> Fix: insert/update/delete do not return until changeHandler called

src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/errors/config.js, src/userbase-js/src/errors/db.js, src/userbase-js/src/statusCodes.js, src/userbase-js/src/utils.js, src/userbase-js/src/ws.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/statusCodes.js, src/userbase-server/ws.js
1. The server will always send transactions in sequence.
2. The client will always apply transactions in sequence.
3. The client will apply batches of transactions received from the server one at a time in the order received from the server.
4. A client cannot open multiple web socket connections.
5. `userbase.openDatabase` is now idempotent. For every successive call to open database, the change handler is replaced with the latest call.
6. `userbase.init` is now idempotent. Once set, the app id and endpoint cannot be changed to something different. The key not found handler is replaced with the latest call.
Unfortunately since each major change is directly dependent on others, I think this whole PR needs to be reviewed in 1 pass as a collective change. Almost every line is critical.
I …
=> Db correctness changes

src/userbase-js/src/auth.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/statusCodes.js, src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx, src/userbase-server/admin.js, src/userbase-server/app.js, src/userbase-server/server.js, src/userbase-server/statusCodes.js, src/userbase-server/user.js
Copied from @dvassallo 's message on Basecamp with some things left out:
1. When you sign up for an admin account, the system will automatically create a "Trial" app for you.
2. When you click on the Trial app, you get a message at the top that says that the trial app can only have 3 users.
3. We won't allow the creation of new apps unless you have a subscription. We verify this server-side and return an error if you try to create a new App and you don't have a subscription.
4. On signUp, we check if the app is a Trial type, and we return an error if there are already 3 users AND the account doesn't have a subscription.
5. Once the account gets a subscription, the Trial app becomes a regular app. The admin can rename it and keep using it just like any app.
- Someone using the open source …
=> Payment Plan working as defined in spec

cypress/integration/login.spec.js, src/userbase-js/src/auth.js, src/userbase-js/src/localData.js, src/userbase-js/src/ws.js
Session storage takes precedence, meaning if there's a session in both sessionStorage and localStorage, the session in sessionStorage will init.
=> Use session storage if rememberMe false

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/UnknownError.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx, src/userbase-server/admin.js
- If an admin's payment status fails to load on sign in, prevents them from seeing the free version of the app. They instead see the error message in the screenshot below
- Improves loading logic and implements error handling for the endpoints that interact with the Stripe API
- All errors with status >= 500 now display a message similar to the one in the screenshot (sometimes they have slightly more detail e.g. Oops! Something went wrong updating your account. blah blah blah)
=> Finish stripe payments

src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx
- if does not work as expected, defaults to ISO 8601
=> Date formatter working for all modern browsers

cypress/integration/signup.spec.js, nodemon.json, src/proof-of-concept/client/App.jsx, src/userbase-js/src/auth.js, src/userbase-js/src/errors/auth.js, src/userbase-js/types/index.d.ts, src/userbase-server/admin-panel/webpack.config.js, src/userbase-server/admin.js, src/userbase-server/peers.js, src/userbase-server/server.js, src/userbase-server/setup.js, src/userbase-server/user.js, src/userbase-server/utils.js
We've received a feature request from multiple people asking to enable admins to programmatically update values associated with individual users. Here's [one example](https://twitter.com/Dayhaysoos/status/1222914997728223234). This feature will enable admins to programmatically set a payment flag on a user and tie any other data to a user that only the admin can create.
This is done via an `internalProfile` object that only the admin can write to and only the user can read from. This object is not encrypted.
- Admins will need an "access token" to include in the request to update a user's internal profile. Admins acquire the access token via a new REST endpoint `GET /access-tokens`.  We don't link to this endpoint from the Admin panel for now. Early beta testers of this feature can visit …
=> Admin access token + Internal profile

cypress/integration/db-correctness.spec.js, cypress/integration/forogtPassword.spec.js, cypress/integration/signup.spec.js, cypress/support/utils.js, src/proof-of-concept/client/components/User/UserForm.jsx, src/proof-of-concept/client/components/User/logic.js, src/userbase-js/src/auth.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/errors/config.js, src/userbase-js/src/errors/db.js, src/userbase-js/src/index.js, src/userbase-js/src/utils.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-js/types/test.ts, src/userbase-server/crypto/hkdf.js, src/userbase-server/crypto/index.js, src/userbase-server/crypto/scrypt.js, src/userbase-server/server.js, src/userbase-server/user.js, src/userbase-server/utils.js
Our top feature request so far is to let users reset their password. Userbase didn’t initially allow this because the user’s encryption key is stored on the Userbase server encrypted with a key derived from the user’s password. When the user signed in, the original password was needed to first retrieve and then decrypt the encryption key.
However, Userbase also allows you to let users automatically sign in after they close their browser by setting the `rememberMe` option to `'local'` in the signUp and signIn APIs. In this case, the user’s encryption key gets saved in the browser’s local storage.
Now, with the addition of the forgotPassword API, so long as the user still has access to a device that was previously used to log in with `rememberMe` set to `'local'`, the user will be able to …
=> Forgot Password

cypress/integration/db.spec.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/db.js
- tested null, boolean, string, number & object types as items (+ arrays)
- changed wording of "*TooLong" error messages slightly
=> Allow major primitive types as items & added tests for db inputs

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/app.js, src/userbase-server/server.js, src/userbase-server/user.js
Allows an admin to retrieve a user's metadata via a REST endpoint `GET /user {accessToken, appId, userId}`. This enables an admin to see a user's internal profile the admin sets using the feature from #100.
- displays the access token in the admin panel (additional language likely needed linking to docs)
- The API both strips away user's detailed data in the response (e.g. the user's salts) & converts the response to camel case (e.g. `internal-profile` to `internalProfile`) before sending to client
Update: also added [this small commit](https://github.com/encrypted-dev/userbase/pull/108/commits/c9dc8739957137ada860f300834886b10af4f443) to fix a totally separate minor bug where the admin's email and full name would not update on page refresh if they were changed on the server by a separate …
=> Add GetUser Admin API

cypress/integration/login.spec.js, src/userbase-js/src/api/auth.js, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/logic.js, src/userbase-server/admin.js, src/userbase-server/app.js
Usernames containing the "+" character could sign up through the SDK, but could not sign in.
This is because the username was passed as a non-encoded query param to the server, resulting in the "+" converting to a space.
This PR fixes this issue in signIn() by encoding the query param before sending it to the server.
This PR also fixes this issue in the admin panel by simply passing all params in the JSON body of each request, rather than as query params.
Special thank you to Luther for reporting this bug.
=> Fix plus sign encoding

cypress/integration/db.spec.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/db.js
If the item provided to insertItem(), updateItem(), or putTransaction() is not serializable to JSON (in other words, `JSON.stringify(item) === undefined`), then the function throws `ItemInvalid`. See [this link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) for further discussion on what is serializable to JSON.
- also added tests for putTransaction() in this PR
=> Added ItemInvalid error to insertItem, updateItem, and putTransaction

src/userbase-js/src/config.js
The userbase framework is not called until it is in the browser, but it is imported during the building of the static assets in Gatsby making it problematic to set values on window.
Read more in [Gatsby docs](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules).
Userbase is a great framework for Gatsby and would probably benefit from supporting it.
=> Window undefined on Gatsby build creates problems

src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/ws.js
- prevents malicious client from providing another user's database id
- relies on openDatabase, which makes sure that user has access to database before opening it
=> [fix] Server ensures user has db open before allowing writes

src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/utils.js, src/userbase-server/admin.js, src/userbase-server/server.js, src/userbase-server/setup.js
Some touch ups to the admin access token introduced in #100 .
- admins can now generate access tokens and provide a label.
- admins must provide their password to generate an access token.
- admins must save the access token upon creation (the server hashes them before storing, so the admin needs to save the pre-image to the hash).
- admins can now delete access tokens.
- implemented a list view of access tokens table similar to app users.
Here's what it looks like now:
=> Add ability to generate & delete access token + hash it before storage

src/userbase-server/admin.js, src/userbase-server/app.js, src/userbase-server/purge.js, src/userbase-server/server.js, src/userbase-server/setup.js, src/userbase-server/user.js, src/userbase-server/utils.js, src/userbase-server/ws.js
The purge process gets scheduled to run at a random time between 1am and 3am PST every night.
The process starts by scanning the admin, app, and user tables to see if items have been deleted for more than 30 days. If an item has been deleted for more than 30 days, the process places the item in its respective "deleted" table, thereby scheduling it for deletion. For example, if a user has been deleted for 31 days, the purge process will place it in the deleted-users table.
The purge process then scans the "deleted" tables and purges deleted items.
For now, the purge process does not actually remove deleted data; instead, it logs the exact data that will be deleted. Once the logs confirm the code is executing correctly in prod, we plan to uncomment the code that actually removes deleted …
=> Purge deleted data

cypress/integration/Admin API/app.spec.js, src/userbase-server/app.js, src/userbase-server/server.js, src/userbase-server/user.js
This feature enables an admin to query for all of an app's users using their app ID and access token.
Thank you again to @raae for the suggestion!
```
GET https://v1.userbase.com/v1/admin/apps/:appId?nextPageToken="<explained below>"
Authorization: Bearer <access token>
```
```
{
appId,
appName,
creationDate: <Date created as ISO string>,
deleted: <Date deleted as ISO string>,
users: [{
userId,
username,
email,
profile,
protectedProfile,
creationDate,
deleted
}],
nextPageToken: <Explained below>
}
```
`nextPageToken` is an optional pagination token. If the Userbase Admin API returns a `nextPageToken` in the response body, it means the developer must provide it in the next request to get the next page of users.
Here is what querying for all of an app's users would look like (need to …
=> GetApp REST endpoint in Admin API

src/userbase-js/src/auth.js, src/userbase-js/src/errors/config.js
Chrome requires websites use https when accessing the WebCrypto API. This PR throws the error `WebCryptoUnavailable` in init() if the WebCrypto API is unavailable.
See #125
=> Throw error if WebCrypto API is unavailable

src/userbase-js/src/auth.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/statusCodes.js, src/userbase-server/user.js
If a user deletes their account and then tries to sign in to the same account, they get the confusing "UsernameOrPasswordMismatch" error. This PR adds the error "UserPendingDeletion" to make it clear that is why the user cannot sign in when providing the correct password after deleting the account.
Shoutout to @rhucle for highlighting this in #134 .
=> If user pending deletion, say so in signIn if provided correct password

cypress/integration/Admin API/app.spec.js, src/userbase-server/admin.js, src/userbase-server/app.js, src/userbase-server/server.js
Some final touchups on the Admin API to make it simpler.
- GetApp now only returns app metadata.  
- GetApp from #122 is now referred to as ListUsers. ~No functional changes to this REST endpoint.~ (Update: removed app metadata from ListUsers)
- Added ListApps.
```
GET https://v1.userbase.com/v1/admin/apps/:appId
Authorization: Bearer <access token>
```
```
{
appId,
appName,
creationDate: <Date created as ISO string>,
deleted: <Date deleted as ISO string>,
}
```
```
GET https://v1.userbase.com/v1/admin/apps/:appId?nextPageToken="<explained below>"
Authorization: Bearer <access token>
```
```
{
users: [{
userId,
username,
email,
profile,
protectedProfile,
creationDate,
deleted
}],
nextPageToken: <Explained below>
}
```
```
GET https://v1.userbase.com/v1/admin/apps?nextPageToken="<explained …
```
=> Admin API added ListUsers & ListApps, GetApp only returns app metadata

src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/api/auth.js, src/userbase-js/webpack.common.js
- Removed corejs3 polyfill to allow developers to use their own polyfills/not pollute globals (more on this [here](https://babeljs.io/docs/en/babel-plugin-transform-runtime#why)).
- Replaced axios with XMLHtthRequest.
Thanks to @rhucle for the suggestions in #133
=> SDK package size cleanup

src/userbase-js/.babelrc
Following #137, also remove core-js imports in the ES module build, which is the one that webpack/rollup bundlers will be using.
=> Remove core-js imports in ESM build

src/userbase-js/src/auth.js, src/userbase-js/src/errors/auth.js, src/userbase-server/user.js
- unnecessary because JS automatically converts object keys to strings ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects))
=> Removed ProfileKeyMustBeString error from userbase-js

cypress/integration/Admin API/user.spec.js, src/userbase-js/src/auth.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/payments.js, src/userbase-js/src/payments.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/StripeDataTable.jsx, src/userbase-server/app.js, src/userbase-server/setup.js, src/userbase-server/stripe.js, src/userbase-server/user.js
With #148 , when an admin set a subscription plan with a trial period on an app, a new user signing up to the app would not be able to call `openDatabase` successfully right off the bat. The user would need to call `purchaseSubscription` and provide their credit card in the Stripe Checkout form to begin their trial and successfully call `openDatabase`.
Now, with this PR, when a user signs up for an app with a subscription plan with a trial period set, the user will be able to call `openDatabase` until the trial expires. And when the user calls `purchaseSubscription`, we charge the user immediately, it does not begin a trial.
The user's `subscriptionStatus` should never be set to 'trialing' now. A developer will know a user is in trial mode because we return `trialExpirationDate` on users. …
=> Apps with trial period set now start trial on signUp

src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/AdminForm.jsx, src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/config.js
The buttons on the [pricing page](https://userbase.com/pricing/) can now link to #upgrade and #enable-payments to automatically trigger the logic for each.
- if admin is not signed in, they can create a new account or sign in, and then the signed in logic is triggered
- if signed in
- if the admin already has the plan, do nothing
- if the admin does not have the plan, simulate clicking the respective button
On enable-payments, it displays the modal `window.confirm('Purchase the payments add-on for $129 per year!')` before simulating the button click to buy the add-on.
Unfortunately I couldn't get Chrome to consistently render the #edit-account page before displaying the modal, so it gets stuck in the loading state until the admin responds to the modal. It works consistently in Safari and …
=> Userbase hompage pricing button links automatically trigger actions

src/userbase-js/CHANGELOG.md, src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/auth.js, src/userbase-js/src/localData.js, src/userbase-server/admin.js, src/userbase-server/user.js, src/userbase-server/utils.js
When a user signs in to Userbase, they receive a session that expires after 24 hours, allowing the user to automatically sign back in to Userbase on subsequent visits to an app for 24 hours when **rememberMe** is set to `'session`' or `'local'`. Userbase devs use [`userbase.init()`](https://userbase.com/docs/sdk/init/) to automatically sign users back in. If the user attempts to call `userbase.init()` *after* the session has expired, the user will not be automatically signed in and the response to init() will instead include the user's `lastUsedUsername`.
Before this PR, userbase-js would make a request to the server to find out the user's session has expired.
Now, we store the session expiration date locally, allowing init() to return immediately without needing to make a request to the …
=> userbase-js init now returns immediately if user's session has expired

src/proof-of-concept/client/components/User/logic.js, src/userbase-js/src/Crypto/aes-gcm.js, src/userbase-js/src/Crypto/aes-kw.js, src/userbase-js/src/Crypto/ecdh.js, src/userbase-js/src/Crypto/ecdsa.js, src/userbase-js/src/Crypto/index.js, src/userbase-js/src/api/auth.js, src/userbase-js/src/auth.js, src/userbase-js/src/ws.js, src/userbase-server/crypto/ecdsa.js, src/userbase-server/crypto/index.js, src/userbase-server/server.js, src/userbase-server/user.js
- New users generate ECDSA & ECDH key pairs, then wrap them using key wrappers derived from their seed. The server then stores public keys, wrapped private keys, and salts (as well as the ECDH public key digitally signed by the ECDSA key).
- All future logins, the server authenticates the user by verifying the user can digitally sign a random message using the private key associated with the stored ECDSA public key.
- Old clients will still work normally using DH.
- Old users signing in with a new client will automatically generate ECDSA + ECDH key pairs. The server stores them and deletes DH key, and will use the ECDSA public key authentication process described above going forward.
=> Transition from DH to ECDSA-ECDH

cypress.json, cypress/integration/Admin API/user.spec.js, cypress/integration/updateUser.spec.js, src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/errors/config.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-js/types/test.ts, src/userbase-server/db.js, src/userbase-server/peers.js, src/userbase-server/server.js, src/userbase-server/user.js, src/userbase-server/ws.js
Credit to @raae for the suggestion in #172
- [init()](https://userbase.com/docs/sdk/init/) accepts a callback function as a parameter called `updateUserHandler`
- When a user is updated via [updateUser()](https://userbase.com/docs/sdk/update-user/) in the SDK from any client, or [Update User](https://userbase.com/docs/api/update-user/) in the Admin API, the callback function is invoked with the following object:
- user
- username
- userId
- authToken
- creationDate
- passwordChanged (only if changed)
- email (only if set)
- profile (only if set)
- protectedProfile (only if set)
- paymentsMode (only if set)
- subscriptionStatus (only if set)
- trialExpirationDate (only if set)
- cancelSubscriptionAt (only if set)
- fixed a couple minor bugs
- `updateUser()` now handles the …
=> Update user handler

src/userbase-server/admin-panel/components/Admin/EditAdmin.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx, src/userbase-server/admin.js, src/userbase-server/app.js, src/userbase-server/user.js
- has all the same features as an admin account with active SaaS subscription
- must contact support to enable payments add-on + storage
=> Can manually set 'alt-saas-subscription-status' on admin to 'active'

src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx
Small UI tweak for the active and pending deletion user tables. Changing `overflow-scroll` -> `overflow-auto` in order to only show scroll bars if overflow exists.
Original:
Proposed:
=> UI update for active & pending deletion user tables

cypress/integration/db-correctness.spec.js, src/userbase-js/CHANGELOG.md, src/userbase-js/package-lock.json, src/userbase-js/package.json, src/userbase-js/src/api/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/ws.js, src/userbase-server/package-lock.json, src/userbase-server/package.json, src/userbase-server/server.js
File storage works by attaching a file to an item. Each file has a distinct file encryption key that is also stored alongside the item on the server (the file encryption key is encrypted using the database’s encryption key).
Further, once a user's database exceeds a certain size, the client initiates a bundling process that bundles all items in the database together for performance reasons. This process is explained further [in the Userbase architecture spec](https://github.com/encrypted-dev/userbase/blob/78e5fbf9cbfa7562acb3584c3ee85312c60266be/docs/userbase_architecture.md#bundling).
In userbase-js 2.1.0, when the bundling process is triggered, the client would not correctly bundle file encryption keys alongside items, nor would it correctly read the file metadata back from the bundle. …
=> Fix getFile() after user has inserted a large amount of data into database

cypress/integration/db.spec.js, src/userbase-js/src/db.js, src/userbase-server/db.js, src/userbase-server/server.js
As requested by @jneterer  in #189, this offers a convenient way to retrieve a single database's metadata using its name or ID.
=> getDatabases() takes databaseName or databaseId as filter param

src/userbase-js/src/errors/db.js
Hi, 
Thanks for this awesome piece of software! 
I was experimenting with the **shareDatabase** functionality when I stumbled upon the following error:
> User not verified. Either verify user before sharing database, or set requireVerified to **true**.
It took me a minute to realise the latter should be "false" if you don't want to verify a user.
This fix changes **true** to **false** in the thrown error message.
=> Fix error message for 'UserNotVerified' error

src/userbase-js/types/index.d.ts
Tiny fix from
```
getDatabases(params?: { databaseName?: string, databaseId?: string }): Promise<DatabasesResult[]>
```
To
```
getDatabases(params?: { databaseName?: string, databaseId?: string }): Promise<DatabasesResult>
```
=> getDatabases response type fix

cypress/integration/file-storage.spec.js, src/userbase-js/src/db.js
This fixes #220. I did not wrap the `ws.request` in a promise as suggested, because I thought this was easier  since the transferred size is calculated already.
=> fix #220: add progress handler callback function to uploadFile

cypress/integration/Database Correctness/open-database.spec.js, cypress/integration/Database Correctness/transaction.spec.js, src/userbase-js/src/db.js
- doesn't cause ServiceUnavailable error anymore, and allows database functions to return successfully even if changeHandler throws
=> If developer's code has error in their changeHandler, SDK logs it

cypress/integration/db.server-side-encryption.spec.js, src/userbase-js/CHANGELOG.md, src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/errors/db.js, src/userbase-js/types/index.d.ts, src/userbase-server/purge.js, src/userbase-server/server.js, src/userbase-server/utils.js
init() requires `allowServerSideEncryption` param when an app is set to the server-side encryption mode, or a developer uses the server-side encryption mode at all.
=> Allow server side encryption param in init()

package-lock.json, src/proof-of-concept/package-lock.json, src/proof-of-concept/webpack.config.js, src/userbase-js/package-lock.json, src/userbase-js/src/auth.js, src/userbase-js/src/config.js, src/userbase-js/src/errors/auth.js, src/userbase-server/admin-panel/App.jsx, src/userbase-server/admin-panel/components/Admin/logic.js, src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx, src/userbase-server/admin-panel/components/Dashboard/Dashboard.jsx, src/userbase-server/admin-panel/components/Dashboard/logic.js, src/userbase-server/admin.js, src/userbase-server/app.js, src/userbase-server/package-lock.json, src/userbase-server/purge.js, src/userbase-server/server.js, src/userbase-server/setup.js, src/userbase-server/user.js
Allows admins to limit usage of an app ID to domains in a whitelist. Requested by @jneterer in #228.
Makes sure the [origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) sent by the browser is included in the app's whitelist.
If an admin has 0 domains in their whitelist - which is the case for all current apps - the app ID works from any domain.
Some browsers don't always include the origin header. If the header is not sent along with the request, the browser automatically passes validation. See [this post](https://stackoverflow.com/questions/42239643/when-do-browsers-send-the-origin-header-when-do-browsers-set-the-origin-to-null) for more info on when browsers pass the header.
=> Domain whitelist

cypress/integration/Database Correctness/attribution.spec.js, cypress/integration/Database Sharing/access-control.spec.js, src/userbase-js/src/db.js, src/userbase-js/src/errors/auth.js, src/userbase-js/src/errors/db.js, src/userbase-js/src/ws.js, src/userbase-js/types/index.d.ts, src/userbase-js/types/test.ts, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/ws.js
This PR enables item creators to set or modify write access permissions on individual items in a database. Thank you to @shamblesides for the feature request in #208!
An item creator can for example only allow themselves to update or delete an item:
```
userbase.insertItem({ 
databaseName, 
item, 
writeAccess: { onlyCreator: true } 
})
```
An item creator can also only allow particular users to update or delete an item:
```
userbase.updateItem({ 
databaseName,
itemId,
item,
writeAccess: {
users: [{ username: 'bob' }] 
}
})
```
The item creator can remove the write access permissions set on an item at any point too.
```
userbase.updateItem({
databaseName,
itemId,
item,
writeAccess: null 
})
```
Note that the database owner has root privileges, and can override any item-level settings set …
=> Item-level access control (#208)

.github/workflows/e2e-tests.yml, cypress/integration/Database Correctness/bundling.spec.js, cypress/integration/Database Sharing/share-database.spec.js, cypress/integration/Database Sharing/share-token.spec.js, cypress/support/utils.js, src/userbase-js/CHANGELOG.md, src/userbase-js/src/api/db.js, src/userbase-js/src/api/utils.js, src/userbase-js/src/config.js, src/userbase-js/src/db.js, src/userbase-js/src/ws.js, src/userbase-server/db.js, src/userbase-server/server.js, src/userbase-server/utils.js, src/userbase-server/ws.js, test/browser1/index.html, test/browser2/index.html, test/development.js
When a database grows 50kb, the Userbase client will bundle the database up, compress it, encrypt it, then store it on the server. Next time the user signs in and loads their data, they load the database from the bundle for speedy loading. This process is described further [here](https://github.com/smallbets/userbase/blob/e73a90e677f4ddb8e597eef3050778a4c35627c8/docs/userbase_architecture.md#bundling).
In userbase-js v2.7.0 (#252), a race condition was introduced: if 2 clients were bundling the same database at the same time, it's possible one client could overwrite another's bundle, and then lose the race to store the bundle's encryption key to the other client. So in this rare circumstance, the database wouldn't load the next time a user tries to open it, since the stored encryption key …
=> Bundling process race condition patched

src/userbase-js/src/db.js, src/userbase-js/src/ws.js
When calling `openDatabase`, the `changeHandler` gets executed before the function returns successfully. This way developers are guaranteed to have all of a database's data loaded before `openDatabase` returns.
Prior to this PR, developers couldn't pass triggers into the `changeHandler` to be executed on database load, or read files on database load. Developers would need to wait until `openDatabase` returned successfully to do anything like that.
This PR allows developers to call triggers or read files on database load, before the `changeHandler` finishes executing.
This is particularly useful in the following case:
- a user needs all their data in a database loaded in succession
- some of the users' data is stored as files
- with this PR, the changeHandler can retrieve a file before …
=> Change handler triggers

src/userbase-js/types/index.d.ts
Adding an optional generic type to the Item interface allows developers to optionally declare what type `Item.item` will be. If no type is provided, it defaults to the original type "any".
For example, if I have an interface Book `interface Book { isbn: string; }`, I could define a contract that represents the book as an item saved in a database `type BookItem = Item<Book>`. Lastly, I could use `BookItem` to define the return type from our `changeHandler` in `userbase.openDatabase` like so:
```
userbase.openDatabase({
databaseName: 'my_database_name',
changeHandler: (items: BookItem[]) => {
items.forEach((item: BookItem) => {
console.log('book isbn: ', item.item.isbn);
});
}
});
```
=> Add Optional Generic Type to Item Interface
